baseURL = "https://katherinemwood.github.io/"
languageCode = "en-us"
title = "Katherine Wood"
theme = "personal-web"
copyright="© Katherine Wood"
googleAnalytics = "UA-100181660-1"
disqusShortname = "kmwblog"
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params.intro]
  main = "Katherine Wood"

[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['projects'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "post"
  projects = "projects"
  publications = "publications"
  

[params.sidebar]
  backgroundImage = "/images/path.jpeg" # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
  gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = "/images/portrait.jpeg" # - default "/images/edna-west.jpg"
[params.assets]
  favicon = "/images/icon.png"
  customCSS = ""

[params.social]
  github = "https://github.com/katherinemwood"
  twitter = "https://twitter.com/kathmwood"
  linkedin = "https://www.linkedin.com/in/katherine-m-wood/"

[params.contact]
  email = ""
  text= "" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About Me"
  url = "/about/"
  weight = -120

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  title = "Projects"
  url = "/projects/"
  weight = -100

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  title = "Blog"
  url = "/post/"
  weight = -110
  
[[menu.main]]
  identifier = "publications"
  name = "Publications"
  title = "Publications"
  url = "/publications/"
  weight = -90

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
